# silver_ex_python

In [36]:
import numpy as np
import pandas as pd

### 1- Write a program that takes two numbers as input and calculates their sum, difference, product, and quotient.

In [5]:
first_num , second_num = map(float, input('Please enter two number separated with space:').split())
print('First_num:', first_num, 'Second_num:', second_num)
print('Sum: ', first_num + second_num)
print('Diff: ', first_num - second_num)
print('Prod: ', first_num * second_num)
print('Quot: ', first_num / second_num)

First_num: 24.0 Second_num: 6.0
Sum:  30.0
Diff:  18.0
Prod:  144.0
Quot:  4.0


### 2- Write a program that takes two numbers as input and determines whether the first number is greater than, less than, or equal to the second number.

In [7]:
first_num , second_num = map(float, input('Please enter two number separated with space:').split())
print('First_num:', first_num, 'Second_num:', second_num)
if first_num < second_num:
    print( first_num , 'is lesser than', second_num)
elif second_num < first_num:
    print(first_num, 'is grater than', second_num)
else:
    print('Numbers are equal.')

First_num: 2.0 Second_num: 2.0
Numbers are equal.


### 3- Write a program that takes an initial value and applies different assignment operators (e.g., +=, -=, *=) to modify the value and print the result.

In [8]:
init_value = float(input())
print('Original number: ', init_value)
init_value += 3
print('Modified number(+3): ', init_value)
init_value -= 5
print('Modified number(-5): ', init_value)
init_value *= 2
print('Modified number(*2): ', init_value)


Original number:  3.0
Modified number(+3):  6.0
Modified number(-5):  1.0
Modified number(*2):  2.0


### 4- Write a program that takes a person's age as input and determines whether they are eligible to vote (consider the legal voting age is 18).

In [9]:
age = int(input('Please enter your age: '))
print('Your age:', age)
if age < 18:
    print("You can`t vote now. Please wait until 18.")
else:
    print('congratulations! you can vote.')

Your age: 19
congratulations! you can vote.


### 5- Write a program that takes a number as input and checks whether it is positive, negative, or zero.

In [11]:
sign_num = float(input('Please enter a number: '))
print('Input number: ', sign_num)
if sign_num < 0:
    print('Negative')
elif sign_num > 0:
    print('Positive')
else:
    print('Zero')

Input number:  5.0
Positive


### 6- Write a program that takes a string as input and prints each character on a separate line using a for loop.

In [12]:
in_string = input()
print('Input string: ', in_string)
for i in in_string:
    print(i)

Input string:  Pedram
P
e
d
r
a
m


### 7- Write a program that takes a number as input and prints all the even numbers up to that number using a while loop.

In [13]:
a = int(input('Please enter number: '))
print('Input number: ', a)
x = 1
while x <= a:
    if (x%2) != 0:
        print(x, end=" ")
    x += 1

Input number:  10
1 3 5 7 9 

### 8- Write a program that takes a list of words and prints the length of each word that starts with the letter 'a'.

In [15]:
in_lst = list(input().split())
print('Input list:' , in_lst)
for i in in_lst:
    if i[0] == 'a':
        print('Length of {0}: {1}'.format(i, len(i)))


Input list: ['arian', 'pedram', 'asqar', 'sadra', 'mohammad']
Length of arian: 5
Length of asqar: 5


### 9- Create two lists of numbers and concatenate them into a single list.

In [17]:
a_list = [1, 2, 3 , 4, 5]
b_list = [6, 7, 8, 9, 10]
cancat_list = a_list + b_list
print(cancat_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


### 10- Create a list of numbers and print the sum of the first and last elements.

In [29]:
list_example = [1, 3, 4 ,6 , 234 , 6]
print('Sum of first and last elements: ', list_example[0] + list_example[-1])

Sum of first and last elements:  7


### 11- Create a list of numbers and change the value of the third element.

In [21]:
change_list = [1, 2, 5, 5, 6, 7, 8, 9, 10]
change_list[2] = 3
print(change_list)

[1, 2, 3, 5, 6, 7, 8, 9, 10]


### 12- Create a list of strings and print a sublist containing the last two elements.

In [23]:
u_list  = ['My', 'name', 'is', 'Pedram', 'Arianmanesh']
sub_list = []
sub_list.append(u_list[-2])
sub_list.append(u_list[-1])
print(sub_list)

['Pedram', 'Arianmanesh']


### 13- Create a tuple of strings and print the elements in reverse order.

In [28]:
rev_tuple = ('first', 'second', 'third')
print(rev_tuple[::-1])

('third', 'second', 'first')


### 14- Create a tuple of numbers and calculate the sum of the first and last elements.

In [31]:
first_last_touple = (1, 3, 4 ,6 , 234 , 8)
print('Sum of first and last elements: ', first_last_touple[0] + first_last_touple[-1])

Sum of first and last elements:  9


### 15- Create a tuple of numbers and change the value of the third element (Note: Tuples are immutable, so you'll need to convert it to a list, modify it, and then convert it back to a tuple).

In [33]:
change_tuple = (1, 2, 2, 4, 5)
help_list = list(change_tuple)
help_list[2] = 3
change_tuple = tuple(help_list)
print(change_tuple)

(1, 2, 3, 4, 5)


### 16- Create a tuple of strings and print a subtuple containing the last two elements.

In [36]:
u_tuple  = ('My', 'name', 'is', 'Pedram', 'Arianmanesh')
sub_tuple = []
sub_tuple.append(u_tuple[-2])
sub_tuple.append(u_tuple[-1])
sub_tuple = tuple(sub_tuple)
print(sub_tuple)

('Pedram', 'Arianmanesh')


### 17- Create a dictionary representing a product with keys for "name", "price", and "quantity". Print the dictionary.

In [38]:
product_info = {'name':'Golabi', 'price':'30T per kilogram', 'quantity':'30 kilogram'}
for i in product_info:
    print(i,":", product_info[i]) 

name : Golabi
price : 30T per kilogram
quantity : 30 kilogram


### 18- Create a dictionary representing a person and print the value associated with the "name" key.

In [39]:
person_info = {'name':'Pedram', 'age':'19', 'sex':'male'}
print(person_info['name'])

Pedram


### 19- Create a dictionary representing a product and update the value associated with the "quantity" key.

In [40]:
product_info = {'name':'Golabi', 'price':'30T per kilogram', 'quantity':'30 kilogram'}
product_info['quantity'] = '50 kilogram'
print(product_info['quantity'])

50 kilogram


### 20- Create an empty dictionary and add key-value pairs for "name" and "age" representing a person.

In [41]:
person_empt = {}
person_empt['name'] = 'Ali'
person_empt['age'] = 23
print(person_empt)

{'name': 'Ali', 'age': 23}


### 21- Create a dictionary representing a product and update the value associated with the "quantity" key.

In [42]:
#Repetitious question
product_info = {'name':'Golabi', 'price':'30T per kilogram', 'quantity':'30 kilogram'}
product_info['quantity'] = '50 kilogram'
print(product_info['quantity'])

50 kilogram


### 22- Create two sets of numbers and perform the union operation to combine them into a single set.

In [44]:
set_1 = {1, 2, 4, 5, 3, 6}
set_2 = {1, 3, 5, 6, 7, 0, 8}
united_set = set_1.union(set_2)
print(united_set)

{0, 1, 2, 3, 4, 5, 6, 7, 8}


### 23-
### a) Create a set of numbers and remove a specific element using the remove() method.
### b)Create a set of strings and use the discard() method to remove an element that may or may not be present in the set.

In [46]:
# a
set_remove = {0, 1, 2, 3, 4, 5}
set_remove.remove(0)
print("a:", set_remove)
#.........................................
#b
set_string = {'Pdram', 'Arianmanesh', 'hastam'}
set_string.discard('Asqar')
print('b:', set_string)

a: {1, 2, 3, 4, 5}
b: {'Arianmanesh', 'hastam', 'Pdram'}


### 24- Create a string and repeat it multiple times using the multiplication operator.

In [48]:
rep_string = 'salam '*5
print(rep_string)

salam salam salam salam salam 


### 25- Create a string and print the last character.

In [49]:
name = 'Pedram'
print(name[-1])

m


### 26- Create a string and print a substring using slicing.

In [51]:
str_1 = 'Filoger'
sub_str = str_1[2:-2]
print(sub_str)

log


### 27- Create a string and convert it to uppercase using the upper() method.

In [53]:
low_up_str = 'salam'
low_up_str = low_up_str.upper()
print(low_up_str)

SALAM


### 28- Write a function called calculate_area() that takes the length and width of a rectangle as arguments and returns its area.

In [54]:
def calculate_area(length, width):
    return 2*(length + width)
print(calculate_area(5, 3))

16


### 29- Write a function called add_numbers() that takes two numbers as arguments and returns their sum.

In [55]:
def add_numbers(first_num, second_num):
    return first_num + second_num
print(add_numbers(2, 5))

7


### 30- Write a function called calculate_power() that takes a number and an exponent as arguments and calculates the power of the number. If no exponent is provided, it should default to 2.

In [57]:
def calculate_power(num , exponent= 2):
    return num ** exponent
print(calculate_power(2, 4))
print(calculate_power(2))

16
4


### 31- Write a lambda function to check if a number is divisible by 2.

In [61]:
x = lambda num: "yes" if num%2 == 0 else 'no'
print(x(4))
print(x(3))

yes
no


### 32- Write a function that takes a list of numbers as input and returns the sum of all the numbers using a loop.

In [63]:
def sum_list(list):
    sum = 0
    for i in list:
        sum += i
    return sum
num_list = [1,2,3,4]
print(sum_list(num_list))


10


### 33- Write a function that takes a number as input and calculates its factorial using a loop. For example, the factorial of 5 (5!) is 5 * 4 * 3 * 2 * 1 = 120.

In [64]:
def factroial(n):
    x = 1
    for i in range(1,n+1):
        x *= i
    return x
print(factroial(5))

120


### 34- Write a function that takes a string as input and counts the number of vowels (a, e, i, o, u) in the string using a loop.

In [66]:
def vowel_count(in_string):
    in_string = in_string.lower()
    vowels = ['a', 'e', 'i', 'o', 'u']
    counter = 0
    for i in in_string:
        if i in vowels:
            counter += 1
    return counter
print(vowel_count('Pedram'))

2


### 35- Write a function that takes a number as input and prints the Fibonacci sequence up to that number using a loop. The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones (e.g., 0, 1, 1, 2, 3, 5, 8, ...).

In [76]:
def fibo_loop(n):
    fibo_list = [0, 1]
    for i in range(2, n+1):
        fibo_list.append(fibo_list[i-1]+fibo_list[i-2])
    for i in range(n):
        print(fibo_list[i], end=' ')
fibo_loop(7)


0 1 1 2 3 5 8 

### 36- Write a recursive function that takes a number as input and calculates its factorial. Hint:
### The factorial of a number n can be calculated as n * factorial(n-1).

In [67]:
def factroial_recur(n):
    if n ==1:
        return 1
    else:
        return n*factroial_recur(n-1)
print(factroial_recur(5))

120


### 37- Write a recursive function that takes a number as input and returns the nth number in the Fibonacci sequence. Hint: The nth number can be calculated as fibonacci(n-1) + fibonacci(n-2).

In [111]:
def fibo_recur(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibo_recur(n-1) + fibo_recur(n-2)
    
print(fibo_recur(6))

8


### 38- Write a program that takes two numbers as input and divides the first number by the second number. Handle the ZeroDivisionError exception if the second number is 0 and print an error message.

In [96]:
def div_handle(a, b):
    print('a:', a, 'b:', b)
    try:
        print('Division a, b: ', a/b)
    except ZeroDivisionError as error:
        print('error:', error)
div_handle(4, 2)
print('..................................')
div_handle(2, 0)

a: 4 b: 2
Division a, b:  2.0
..................................
a: 2 b: 0
error: division by zero


### 39- Write a program that reads the contents of a file specified by the user. Handle the FileNotFoundError exception and print an error message if the file does not exist.

In [97]:
try:
    file = open('salam.txt', 'r')
except FileNotFoundError as error:
    print('error:', error)

error: [Errno 2] No such file or directory: 'salam.txt'


### 40- Write a program that asks the user to enter a positive integer. Use a while loop and exception handling to ensure that the user enters a valid integer. Handle the ValueError exception and prompt the user to enter a valid input.

In [100]:
while True:
    try:
        n = int(input('Please enter an integer number: '))
        print('Input number: ', n)
        break
    except ValueError as error:
        print('error:', error)
        print('try again')

error: invalid literal for int() with base 10: '3.14'
try again
Input number:  2


### 41- Write a program that creates a list of numbers. Handle the IndexError exception and print an error message if the user tries to access an index that is out of range.

In [108]:
number_list = [1, 2, 3, 4, 5]
try:
    n = int(float(input('Please enter index: ')))
    print(number_list[n])
except IndexError as error:
    print('error: ', error)

error:  list index out of range


### 42- Create a 2-dimensional NumPy array with shape (3, 3) filled with zeros

In [115]:
arr = np.array([[0,0,0],[0,0,0],[0,0,0]])
print('shape:' ,arr.shape)

shape: (3, 3)


### 43- Create two NumPy arrays of the same shape and perform element-wise addition.

In [4]:
np_1 = np.array([[4,5], [1,3]])
np_2 = np.array([[9,7],[2,5]])
addition = np.add(np_1, np_2)
print(addition)

[[13 12]
 [ 3  8]]


### 44- Create a 2-dimensional NumPy array and print a 2x2 subarray.

In [8]:

# Creating a 3x3 NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Printing the original array
print("Original array:")
print(arr)

# Printing a 2x2 subarray
sub_arr = arr[:2, :2]
print("\n2x2 subarray:")
print(sub_arr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2x2 subarray:
[[1 2]
 [4 5]]


### 45- Create a 1-dimensional NumPy array and reshape it into a 2x3 array.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshape = arr.reshape(2, 3)
print(reshape)


[[1 2 3]
 [4 5 6]]


### 46- Create a 2-dimensional NumPy array and calculate the mean of each column.

In [13]:
arr_2dim = np.array([[1,2], [3, 4]])
print(arr_2dim.mean(axis=0))

[2. 3.]


### 47- Create a NumPy array and multiply it element-wise with a 1-dimensional array.

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([3, 4, 5])
multiply_arr = np.multiply(arr1, arr2)
print(multiply_arr)

[ 3  8 15]


### 48- Create a pandas DataFrame from a dictionary, where the keys represent column names and the values represent the data.

In [17]:
data = {'fruit':['sib', 'golabi', 'porteghal'],
        'price per kilo':[23, 40, 30]}
pd_df = pd.DataFrame(data)
print(pd_df)

       fruit  price per kilo
0        sib              23
1     golabi              40
2  porteghal              30


### 49- Load a dataset into a desired DataFrame and print the first few rows using the head() method.

In [19]:
df = pd.read_csv('fakenews.csv')
print(df.head(10))

                                                text  label
0  Get the latest from TODAY Sign up for our news...      1
1  2d  Conan On The Funeral Trump Will Be Invited...      1
2  It’s safe to say that Instagram Stories has fa...      0
3  Much like a certain Amazon goddess with a lass...      0
4  At a time when the perfect outfit is just one ...      0
5  When Reese Witherspoon was 17, she had already...      0
6  It’s official! WAGS Miami stars Ashley Nicole ...      0
7  On March 24, 2018, one month and ten days afte...      1
8  A mosque in Georgia is under fire after they s...      1
9  Scott Disick is sticking up for Khloe Kardashi...      1


### 50- Select a specific column from the DataFrame using square brackets notation.

In [23]:
selected = df['text']
print(selected)

0       Get the latest from TODAY Sign up for our news...
1       2d  Conan On The Funeral Trump Will Be Invited...
2       It’s safe to say that Instagram Stories has fa...
3       Much like a certain Amazon goddess with a lass...
4       At a time when the perfect outfit is just one ...
                              ...                        
4981    The storybook romance of WWE stars John Cena a...
4982    The actor told friends he’s responsible for en...
4983    Sarah Hyland is getting real.  The Modern Fami...
4984    Production has been suspended on the sixth and...
4985    A jury ruled against Bill Cosby in his sexual ...
Name: text, Length: 4986, dtype: object


### 51- Sort the DataFrame based on a specific column

In [33]:
pd_sort  = pd_df.sort_values(by=['price per kilo'])
print(pd_sort)

       fruit  price per kilo
0        sib              23
2  porteghal              30
1     golabi              40


### 52- Check for missing values in the DataFrame using the isnull() method.

In [37]:
print(selected.isnull())

0       False
1       False
2       False
3       False
4       False
        ...  
4981    False
4982    False
4983    False
4984    False
4985    False
Name: text, Length: 4986, dtype: bool


### 53- Group the DataFrame by a specific column and calculate the mean, sum, or count of another column.

In [60]:
titanic = pd.read_csv('titanic.csv')
g_titanic = titanic.groupby('Name')
g_titanic.first()

PassengerId  Survived  Pclass     Sex  \
Name                                                                           
Abbing, Mr. Anthony                            846         0       3    male   
Abbott, Mr. Rossmore Edward                    747         0       3    male   
Abbott, Mrs. Stanton (Rosa Hunt)               280         1       3  female   
Abelson, Mr. Samuel                            309         0       2    male   
Abelson, Mrs. Samuel (Hannah Wizosky)          875         1       2  female   
...                                            ...       ...     ...     ...   
de Mulder, Mr. Theodore                        287         1       3    male   
de Pelsmaeker, Mr. Alfons                      283         0       3    male   
del Carlo, Mr. Sebastiano                      362         0       2    male   
van Billiard, Mr. Austin Blyler                154         0       3    male   
van Melkebeke, Mr. Philemon                    869         0       3    male   

                                        Age  SibSp  Parch         Ticket  \
Name                                                                       
Abbing, Mr. Anthony                    42.0      0      0      C.A. 5547   
Abbott, Mr. Rossmore Edward            16.0      1      1      C.A. 2673   
Abbott, Mrs. Stanton (Rosa Hunt)       35.0      1      1      C.A. 2673   
Abelson, Mr. Samuel                    30.0      1      0      P/PP 3381   
Abelson, Mrs. Samuel (Hannah Wizosky)  28.0      1      0      P/PP 3381   
...                                     ...    ...    ...            ...   
de Mulder, Mr. Theodore                30.0      0      0         345774   
de Pelsmaeker, Mr. Alfons              16.0      0      0         345778   
del Carlo, Mr. Sebastiano              29.0      1      0  SC/PARIS 2167   
van Billiard, Mr. Austin Blyler        40.5      0      2       A/5. 851   
van Melkebeke, Mr. Philemon             NaN      0      0         345777   

                                          Fare Cabin Embarked  
Name                                                           
Abbing, Mr. Anthony                     7.5500  None        S  
Abbott, Mr. Rossmore Edward            20.2500  None        S  
Abbott, Mrs. Stanton (Rosa Hunt)       20.2500  None        S  
Abelson, Mr. Samuel                    24.0000  None        C  
Abelson, Mrs. Samuel (Hannah Wizosky)  24.0000  None        C  
...                                        ...   ...      ...  
de Mulder, Mr. Theodore                 9.5000  None        S  
de Pelsmaeker, Mr. Alfons               9.5000  None        S  
del Carlo, Mr. Sebastiano              27.7208  None        C  
van Billiard, Mr. Austin Blyler        14.5000  None        S  
van Melkebeke, Mr. Philemon             9.5000  None        S  

[891 rows x 11 columns]

In [64]:
mean = titanic['Age'].mean()
print('mean of ages: ', mean)

mean of ages:  29.69911764705882


In [65]:
titanic_sum = titanic['Survived'].sum()
print('sum of survived: ', titanic_sum)

sum of survived:  342


In [66]:
titanic.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64